import express from 'express';
import cors from 'cors';
import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';
import webpush from 'web-push';

const app = express();
const PORT = Number(process.env.PORT || 3000);
const APP_ORIGIN = process.env.APP_ORIGIN || '*';
const CRON_INTERVAL_MS = Math.max(10000, Number(process.env.CRON_INTERVAL_MS || 60000));
const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), 'data');
const DB_PATH = process.env.DB_PATH || path.join(DATA_DIR, 'offline-active-reply.db');
let vapidPublicKey = process.env.VAPID_PUBLIC_KEY || '';
let vapidPrivateKey = process.env.VAPID_PRIVATE_KEY || '';
let vapidSubject = process.env.VAPID_SUBJECT || 'mailto:you@example.com';
let vapidAutoGenerated = false;

if (!vapidPublicKey || !vapidPrivateKey) {
    const generatedKeys = webpush.generateVAPIDKeys();
    vapidPublicKey = generatedKeys.publicKey;
    vapidPrivateKey = generatedKeys.privateKey;
    vapidAutoGenerated = true;
}

const PUSH_ENABLED = Boolean(vapidPublicKey && vapidPrivateKey && vapidSubject);

if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
}

if (PUSH_ENABLED) {
    webpush.setVapidDetails(vapidSubject, vapidPublicKey, vapidPrivateKey);
} else {
    console.warn('[push] disabled: VAPID env vars are incomplete');
}

const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');

db.exec(`
CREATE TABLE IF NOT EXISTS device_subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  device_id TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  p256dh TEXT,
  auth TEXT,
  subscription_json TEXT NOT NULL,
  user_agent TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE(user_id, device_id)
);

CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  contact_id TEXT NOT NULL,
  name TEXT,
  persona_prompt TEXT,
  context_limit INTEGER NOT NULL DEFAULT 50,
  active_reply_enabled INTEGER NOT NULL DEFAULT 0,
  active_reply_interval_sec INTEGER NOT NULL DEFAULT 60,
  active_reply_start_time INTEGER DEFAULT 0,
  last_triggered_msg_id TEXT,
  last_triggered_at INTEGER DEFAULT 0,
  last_seen_message_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE(user_id, contact_id)
);

CREATE TABLE IF NOT EXISTS message_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  contact_id TEXT NOT NULL,
  message_id TEXT,
  role TEXT,
  content TEXT,
  type TEXT,
  time INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE(user_id, contact_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  contact_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'text',
  description TEXT,
  time INTEGER NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT 'offline-backend'
);

CREATE TABLE IF NOT EXISTS chat_contexts (
  user_id TEXT NOT NULL,
  contact_id TEXT NOT NULL,
  messages_json TEXT NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (user_id, contact_id)
);

CREATE TABLE IF NOT EXISTS ai_profiles (
  user_id TEXT PRIMARY KEY,
  api_url TEXT NOT NULL DEFAULT '',
  api_key TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '',
  temperature REAL NOT NULL DEFAULT 0.7,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_user_time ON messages(user_id, time);
`);

app.use(cors({ origin: APP_ORIGIN === '*' ? true : APP_ORIGIN, credentials: false }));
app.use(express.json({ limit: '2mb' }));

const upsertContactStmt = db.prepare(`
INSERT INTO contacts (user_id, contact_id, name, persona_prompt, context_limit, active_reply_enabled, active_reply_interval_sec, active_reply_start_time, last_triggered_msg_id, created_at, updated_at)
VALUES (@user_id, @contact_id, @name, @persona_prompt, @context_limit, @active_reply_enabled, @active_reply_interval_sec, @active_reply_start_time, @last_triggered_msg_id, @created_at, @updated_at)
ON CONFLICT(user_id, contact_id) DO UPDATE SET
  name=excluded.name,
  persona_prompt=excluded.persona_prompt,
  context_limit=excluded.context_limit,
  active_reply_enabled=excluded.active_reply_enabled,
  active_reply_interval_sec=excluded.active_reply_interval_sec,
  active_reply_start_time=excluded.active_reply_start_time,
  last_triggered_msg_id=excluded.last_triggered_msg_id,
  updated_at=excluded.updated_at
`);

const upsertSnapshotStmt = db.prepare(`
INSERT INTO message_snapshots (user_id, contact_id, message_id, role, content, type, time, updated_at)
VALUES (@user_id, @contact_id, @message_id, @role, @content, @type, @time, @updated_at)
ON CONFLICT(user_id, contact_id) DO UPDATE SET
  message_id=excluded.message_id,
  role=excluded.role,
  content=excluded.content,
  type=excluded.type,
  time=excluded.time,
  updated_at=excluded.updated_at
`);

const upsertSubscriptionStmt = db.prepare(`
INSERT INTO device_subscriptions (user_id, device_id, endpoint, p256dh, auth, subscription_json, user_agent, created_at, updated_at)
VALUES (@user_id, @device_id, @endpoint, @p256dh, @auth, @subscription_json, @user_agent, @created_at, @updated_at)
ON CONFLICT(user_id, device_id) DO UPDATE SET
  endpoint=excluded.endpoint,
  p256dh=excluded.p256dh,
  auth=excluded.auth,
  subscription_json=excluded.subscription_json,
  user_agent=excluded.user_agent,
  updated_at=excluded.updated_at
`);

const insertMessageStmt = db.prepare(`
INSERT OR IGNORE INTO messages (id, user_id, contact_id, role, content, type, description, time, read, source)
VALUES (@id, @user_id, @contact_id, @role, @content, @type, @description, @time, @read, @source)
`);

const updateTriggerStateStmt = db.prepare(`
UPDATE contacts
SET last_triggered_msg_id = ?, last_triggered_at = ?, last_seen_message_id = ?, updated_at = ?
WHERE user_id = ? AND contact_id = ?
`);

const deleteSubscriptionByEndpointStmt = db.prepare(`DELETE FROM device_subscriptions WHERE endpoint = ?`);
const listSubscriptionsByUserStmt = db.prepare(`SELECT subscription_json, endpoint FROM device_subscriptions WHERE user_id = ?`);
const upsertChatContextStmt = db.prepare(`
INSERT INTO chat_contexts (user_id, contact_id, messages_json, updated_at)
VALUES (@user_id, @contact_id, @messages_json, @updated_at)
ON CONFLICT(user_id, contact_id) DO UPDATE SET
  messages_json=excluded.messages_json,
  updated_at=excluded.updated_at
`);
const getChatContextStmt = db.prepare(`SELECT messages_json FROM chat_contexts WHERE user_id = ? AND contact_id = ?`);
const upsertAiProfileStmt = db.prepare(`
INSERT INTO ai_profiles (user_id, api_url, api_key, model, temperature, updated_at)
VALUES (@user_id, @api_url, @api_key, @model, @temperature, @updated_at)
ON CONFLICT(user_id) DO UPDATE SET
  api_url=excluded.api_url,
  api_key=excluded.api_key,
  model=excluded.model,
  temperature=excluded.temperature,
  updated_at=excluded.updated_at
`);
const getAiProfileStmt = db.prepare(`SELECT * FROM ai_profiles WHERE user_id = ?`);

function normalizeApiUrl(url) {
    const value = String(url || '').trim();
    if (!value) return '';
    if (value.endsWith('/chat/completions')) return value;
    return value.endsWith('/') ? `${value}chat/completions` : `${value}/chat/completions`;
}

function extractTextFromAiResponsePart(part) {
    if (part === null || part === undefined) return '';
    if (typeof part === 'string') return part;

    if (Array.isArray(part)) {
        return part.map((item) => extractTextFromAiResponsePart(item)).filter(Boolean).join('\n');
    }

    if (typeof part !== 'object') return '';

    if (typeof part.text === 'string') return part.text;
    if (part.text && typeof part.text.value === 'string') return part.text.value;
    if (typeof part.value === 'string') return part.value;
    if (typeof part.content === 'string') return part.content;
    if (typeof part.output_text === 'string') return part.output_text;

    if (Array.isArray(part.content)) {
        return part.content.map((item) => extractTextFromAiResponsePart(item)).filter(Boolean).join('\n');
    }

    return '';
}

function extractReplyContentFromAiResponse(data) {
    const choice = data && Array.isArray(data.choices) ? data.choices[0] : null;
    const message = choice && choice.message ? choice.message : null;

    const candidates = [
        { source: 'choices[0].message.content', value: message ? message.content : null },
        { source: 'choices[0].text', value: choice ? choice.text : null },
        { source: 'choices[0].delta.content', value: choice && choice.delta ? choice.delta.content : null },
        { source: 'output_text', value: data ? data.output_text : null },
        { source: 'output[0].content', value: data && Array.isArray(data.output) && data.output[0] ? data.output[0].content : null }
    ];

    for (const candidate of candidates) {
        const text = extractTextFromAiResponsePart(candidate.value).trim();
        if (text) {
            return { content: text, source: candidate.source };
        }
    }

    return { content: '', source: null };
}

function buildActiveReplyInstruction(lastMessage, minutesPassed) {
    if (lastMessage && lastMessage.role === 'user') {
        return `（系统提示：主动发消息模式触发。距离用户上一条消息已过去 ${minutesPassed} 分钟。请在不打断人设的前提下自然接住对方刚才的话；可以轻描淡写解释回复稍晚，也可以直接顺着话题继续。）`;
    }
    return `（系统提示：主动发消息模式触发。距离你上一条消息已过去 ${minutesPassed} 分钟，用户一直没有回复。请像真人间隔一阵后自然续聊：可以补一句、换个轻话题，或分享当下状态/见闻；不要写成系统通知或任务播报。）`;
}

function fallbackMessage(contactName, lastMessage) {
    const name = contactName || '对方';
    if (lastMessage && lastMessage.role === 'user') {
        return `刚刚在忙，现在看到啦。${name}想接着和你聊。`;
    }
    return `${name}隔了一会儿又来找你：我突然想到一件事，想继续和你说。`;
}

function getSubscriptionsByUser(userId) {
    return listSubscriptionsByUserStmt.all(userId).map((row) => {
        try {
            return {
                endpoint: row.endpoint,
                subscription: JSON.parse(row.subscription_json)
            };
        } catch (err) {
            return null;
        }
    }).filter(Boolean);
}

async function sendPushToUser(userId, payload) {
    if (!PUSH_ENABLED) {
        return { enabled: false, delivered: 0, removed: 0 };
    }

    const subscriptions = getSubscriptionsByUser(userId);
    let delivered = 0;
    let removed = 0;

    for (const item of subscriptions) {
        try {
            await webpush.sendNotification(item.subscription, JSON.stringify(payload));
            delivered += 1;
        } catch (err) {
            const statusCode = Number(err && err.statusCode);
            console.error('[push] send failed', statusCode || '', item.endpoint, err && err.message ? err.message : err);
            if (statusCode === 404 || statusCode === 410) {
                try {
                    deleteSubscriptionByEndpointStmt.run(item.endpoint);
                    removed += 1;
                } catch (deleteErr) {
                    console.error('[push] failed to delete expired subscription', deleteErr);
                }
            }
        }
    }

    return { enabled: true, delivered, removed };
}

function getRecentChatContext(userId, contactId) {
    const row = getChatContextStmt.get(userId, String(contactId));
    if (!row || !row.messages_json) return [];
    try {
        const parsed = JSON.parse(row.messages_json);
        return Array.isArray(parsed) ? parsed : [];
    } catch (err) {
        return [];
    }
}

function getAiProfile(userId) {
    return getAiProfileStmt.get(userId) || null;
}

async function generateAiReplyContent(row, minutesPassed) {
    const profile = getAiProfile(row.user_id);
    const recentContext = getRecentChatContext(row.user_id, row.contact_id);
    const instruction = buildActiveReplyInstruction(row, minutesPassed);

    try {
        console.log('[offline-ai] active profile summary', JSON.stringify({
            userId: row.user_id,
            contactId: String(row.contact_id),
            apiUrl: profile ? String(profile.api_url || '').slice(0, 120) : '',
            model: profile ? String(profile.model || '') : '',
            temperature: profile ? Number(profile.temperature || 0.7) : null,
            contextCount: Array.isArray(recentContext) ? recentContext.length : 0,
            contextLimit: Number(row.context_limit || 50) > 0 ? Number(row.context_limit) : 50,
            hasApiKey: !!(profile && profile.api_key)
        }));
    } catch (profileLogErr) {
        console.error('[offline-ai] active profile summary logging failed', profileLogErr);
    }

    if (!profile || !profile.api_url || !profile.api_key || !profile.model) {
        return {
            content: fallbackMessage(row.name || '对方', row),
            usedFallback: true,
            debug: 'missing_ai_profile'
        };
    }

    const messages = [];
    const personaPrompt = String(row.persona_prompt || '').trim();
    const systemSections = [
        `你正在扮演聊天联系人「${row.name || '联系人'}」。`,
        personaPrompt ? `【人设】\n${personaPrompt}` : '',
        '【回复要求】\n- 用聊天口吻自然回复。\n- 不要提到自己是 AI、系统、脚本。\n- 不要写成通知文案。\n- 只输出用户可见的回复正文。'
    ].filter(Boolean);

    messages.push({ role: 'system', content: systemSections.join('\n\n') });

    const contextLimit = Number(row.context_limit || 50) > 0 ? Number(row.context_limit) : 50;
    const trimmedContext = recentContext.slice(-contextLimit).map((message) => ({
        role: message && message.role === 'user' ? 'user' : 'assistant',
        content: String(message && message.content ? message.content : '').slice(0, 1200)
    })).filter((item) => item.content);

    messages.push(...trimmedContext);
    messages.push({ role: 'system', content: instruction });

    try {
        const response = await fetch(normalizeApiUrl(profile.api_url), {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${String(profile.api_key || '').trim()}`
            },
            body: JSON.stringify({
                model: profile.model,
                messages,
                temperature: Number(profile.temperature || 0.7)
            })
        });

        if (!response.ok) {
            const text = await response.text().catch(() => '');
            throw new Error(`API ${response.status}: ${text || response.statusText}`);
        }

        const data = await response.json();
        try {
            const choice = data && Array.isArray(data.choices) ? data.choices[0] : null;
            const message = choice && choice.message ? choice.message : null;
            console.log('[offline-ai] raw response summary', JSON.stringify({
                hasChoices: !!(data && Array.isArray(data.choices) && data.choices.length),
                choiceKeys: choice ? Object.keys(choice) : [],
                messageKeys: message ? Object.keys(message) : [],
                messageContentType: message ? (Array.isArray(message.content) ? 'array' : typeof message.content) : null,
                messageContentPreview: extractTextFromAiResponsePart(message ? message.content : null).slice(0, 200),
                choiceTextPreview: String(choice && choice.text ? choice.text : '').slice(0, 200),
                deltaContentPreview: extractTextFromAiResponsePart(choice && choice.delta ? choice.delta.content : null).slice(0, 200),
                outputTextPreview: String(data && data.output_text ? data.output_text : '').slice(0, 200),
                outputFirstPreview: extractTextFromAiResponsePart(data && Array.isArray(data.output) && data.output[0] ? data.output[0].content : null).slice(0, 200)
            }));
        } catch (logErr) {
            console.error('[offline-ai] raw response summary logging failed', logErr);
        }
        const extractedReply = extractReplyContentFromAiResponse(data);
        const content = String(extractedReply.content || '').trim();
        if (!content) {
            throw new Error('empty ai reply');
        }

        return {
            content: content.replace(/<thinking>[\s\S]*?<\/thinking>/g, '').replace(/<think>[\s\S]*?<\/think>/g, '').trim() || fallbackMessage(row.name || '对方', row),
            usedFallback: false,
            debug: extractedReply.source || 'ai_generated'
        };
    } catch (err) {
        console.error('[offline-ai] generateAiReplyContent failed', err);
        return {
            content: fallbackMessage(row.name || '对方', row),
            usedFallback: true,
            debug: err && err.message ? err.message : 'ai_error'
        };
    }
}

async function createOfflineMessage(row, now) {
    const minutesPassed = Math.max(1, Math.floor((now - Number(row.time || now)) / 60000));
    const generated = await generateAiReplyContent(row, minutesPassed);
    const prompt = buildActiveReplyInstruction(row, minutesPassed);
    const content = generated.content;
    const messageId = `offline-${row.user_id}-${row.contact_id}-${row.message_id}-${now}`;

    const insertResult = insertMessageStmt.run({
        id: messageId,
        user_id: row.user_id,
        contact_id: String(row.contact_id),
        role: 'assistant',
        content,
        type: 'text',
        description: prompt,
        time: now,
        read: 0,
        source: 'offline-backend'
    });

    if (!insertResult.changes) {
        return null;
    }

    updateTriggerStateStmt.run(messageId, now, row.message_id, now, row.user_id, String(row.contact_id));

    const payload = {
        title: row.name ? `${row.name} sent a message` : 'New message',
        body: content,
        tag: `contact-${row.contact_id}`,
        contactId: String(row.contact_id),
        url: `./?contactId=${encodeURIComponent(String(row.contact_id))}&openChat=1`,
        data: {
            contactId: String(row.contact_id),
            messageId,
            url: `./?contactId=${encodeURIComponent(String(row.contact_id))}&openChat=1`
        }
    };

    const push = await sendPushToUser(row.user_id, payload);

    return {
        id: messageId,
        contactId: String(row.contact_id),
        content,
        time: now,
        push,
        usedFallback: generated.usedFallback,
        debug: generated.debug
    };
}

async function runActiveReplyCheck() {
    const rows = db.prepare(`
        SELECT c.user_id, c.contact_id, c.name, c.persona_prompt, c.context_limit, c.active_reply_enabled, c.active_reply_interval_sec, c.active_reply_start_time, c.last_triggered_msg_id,
               s.message_id, s.role, s.content, s.type, s.time
        FROM contacts c
        LEFT JOIN message_snapshots s ON s.user_id = c.user_id AND s.contact_id = c.contact_id
        WHERE c.active_reply_enabled = 1
    `).all();

    const now = Date.now();
    let triggered = 0;

    for (const row of rows) {
        if (!row.message_id) continue;
        if (Number(row.active_reply_start_time || 0) > now) continue;
        if (row.last_triggered_msg_id && row.last_triggered_msg_id === row.message_id) continue;

        const elapsedMs = now - Number(row.time || 0);
        const requiredMs = Math.max(1, Number(row.active_reply_interval_sec || 60)) * 1000;
        if (elapsedMs < requiredMs) continue;

        const created = await createOfflineMessage(row, now);
        if (created) {
            triggered += 1;
        }
    }

    return triggered;
}

app.get('/health', (req, res) => {
    res.json({ ok: true, now: Date.now(), pushEnabled: PUSH_ENABLED, vapidAutoGenerated });
});

app.post('/api/push/subscribe', (req, res) => {
    const body = req.body || {};
    const subscription = body.subscription || {};
    const keys = subscription.keys || {};
    const now = Date.now();
    upsertSubscriptionStmt.run({
        user_id: body.userId || 'default-user',
        device_id: body.deviceId || 'default-device',
        endpoint: subscription.endpoint || '',
        p256dh: keys.p256dh || '',
        auth: keys.auth || '',
        subscription_json: JSON.stringify(subscription),
        user_agent: body.userAgent || '',
        created_at: now,
        updated_at: now
    });
    res.json({ ok: true, pushEnabled: PUSH_ENABLED });
});

app.post('/api/ai-profile', (req, res) => {
    const body = req.body || {};
    const now = Date.now();
    upsertAiProfileStmt.run({
        user_id: body.userId || 'default-user',
        api_url: String(body.apiUrl || '').trim(),
        api_key: String(body.apiKey || '').trim(),
        model: String(body.model || '').trim(),
        temperature: Number(body.temperature || 0.7),
        updated_at: now
    });
    res.json({ ok: true });
});

app.post('/api/chat-context', (req, res) => {
    const body = req.body || {};
    const messages = Array.isArray(body.messages) ? body.messages : [];
    const contextLimit = Number(body.contextLimit || 0) > 0 ? Number(body.contextLimit) : 50;
    upsertChatContextStmt.run({
        user_id: body.userId || 'default-user',
        contact_id: String(body.contactId),
        messages_json: JSON.stringify(messages.slice(-contextLimit)),
        updated_at: Date.now()
    });
    res.json({ ok: true, count: messages.length });
});

app.post('/api/contacts', (req, res) => {
    const body = req.body || {};
    const now = Date.now();
    upsertContactStmt.run({
        user_id: body.userId || 'default-user',
        contact_id: String(body.contactId),
        name: body.name || '',
        persona_prompt: body.personaPrompt || '',
        context_limit: Math.max(0, Math.round(Number(body.contextLimit || 0))) || 50,
        active_reply_enabled: body.activeReplyEnabled ? 1 : 0,
        active_reply_interval_sec: Math.max(1, Math.round(Number(body.activeReplyInterval || 1) * 60)),
        active_reply_start_time: Number(body.activeReplyStartTime || 0),
        last_triggered_msg_id: body.lastActiveReplyTriggeredMsgId || null,
        created_at: now,
        updated_at: now
    });
    res.json({ ok: true });
});

app.get('/api/contacts/active-reply-config', (req, res) => {
    const userId = req.query.userId || 'default-user';
    const contacts = db.prepare(`SELECT * FROM contacts WHERE user_id = ?`).all(userId);
    res.json({ contacts, serverTime: Date.now() });
});

app.post('/api/messages/snapshot', (req, res) => {
    const body = req.body || {};
    const lastMessage = body.lastMessage || {};
    upsertSnapshotStmt.run({
        user_id: body.userId || 'default-user',
        contact_id: String(body.contactId),
        message_id: lastMessage.id || null,
        role: lastMessage.role || 'assistant',
        content: lastMessage.content || '',
        type: lastMessage.type || 'text',
        time: Number(lastMessage.time || Date.now()),
        updated_at: Date.now()
    });
    res.json({ ok: true });
});

app.post('/api/messages/sync', (req, res) => {
    const body = req.body || {};
    const userId = body.userId || 'default-user';
    const since = Number(body.since || 0);
    const messages = db.prepare(`SELECT * FROM messages WHERE user_id = ? AND time > ? ORDER BY time ASC`).all(userId, since);
    res.json({ messages, serverTime: Date.now() });
});

app.post('/api/messages/mark-read', (req, res) => {
    const body = req.body || {};
    const ids = Array.isArray(body.messageIds) ? body.messageIds : [];
    if (ids.length) {
        const placeholders = ids.map(() => '?').join(',');
        db.prepare(`UPDATE messages SET read = 1 WHERE user_id = ? AND id IN (${placeholders})`).run(body.userId || 'default-user', ...ids);
    }
    res.json({ ok: true });
});

app.post('/api/debug/trigger-active-reply', async (req, res) => {
    const body = req.body || {};
    const row = db.prepare(`
        SELECT c.user_id, c.contact_id, c.name, c.persona_prompt, c.context_limit, c.active_reply_enabled, c.active_reply_interval_sec, c.active_reply_start_time, c.last_triggered_msg_id,
               s.message_id, s.role, s.content, s.type, s.time
        FROM contacts c
        LEFT JOIN message_snapshots s ON s.user_id = c.user_id AND s.contact_id = c.contact_id
        WHERE c.user_id = ? AND c.contact_id = ?
    `).get(body.userId || 'default-user', String(body.contactId));

    if (!row || !row.message_id) {
        return res.status(404).json({ ok: false, error: 'contact or snapshot not found' });
    }

    const created = await createOfflineMessage(row, Date.now());
    if (!created) {
        return res.status(409).json({ ok: false, error: 'message already triggered for current snapshot' });
    }

    res.json({ ok: true, message: created, serverTime: Date.now() });
});

setInterval(async () => {
    try {
        const triggered = await runActiveReplyCheck();
        if (triggered > 0) {
            console.log(`[active-reply-cron] triggered ${triggered} message(s)`);
        }
    } catch (err) {
        console.error('[active-reply-cron] failed', err);
    }
}, CRON_INTERVAL_MS);

app.listen(PORT, () => {
    console.log(`offline-active-reply server listening on :${PORT}`);
    console.log(`db path: ${DB_PATH}`);
    console.log(`push enabled: ${PUSH_ENABLED}`);
    if (vapidAutoGenerated) {
        console.log('[push] VAPID keys were auto-generated for this runtime because env vars were missing');
        console.log(`VAPID_PUBLIC_KEY=${vapidPublicKey}`);
        console.log(`VAPID_PRIVATE_KEY=${vapidPrivateKey}`);
        console.log(`VAPID_SUBJECT=${vapidSubject}`);
        console.log('[push] Copy these values into your Render environment variables if you want stable push subscriptions across redeploys');
    }
});

